### ISSUE TITLE
milestone expand/collapse button unexpected wrapping in CosmeticImprovements

### ISSUE THREAD

**Issue by adamosoftware** [adamosoftware/Ginseng8#41]
Cosmetic improvements branch is showing milestone expand/collapse button on new line, when it should be inline within heading. This is on [Dashboard/MyItems](https://github.com/adamosoftware/Ginseng8/blob/CosmeticImprovements/Ginseng8.Mvc/Pages/Dashboard/MyItems.cshtml)

![image](https://user-images.githubusercontent.com/4549398/68406029-17b4f200-014f-11ea-8250-0d3292a73708.png)

![image](https://user-images.githubusercontent.com/4549398/68406055-226f8700-014f-11ea-8872-bf6990284036.png)

**Comment by beccanet** [comment]
I can't test this because I don't have any data that shows on Dashboard/MyItems with the "beccanet" user.
