### ISSUE TITLE
Could not copy the application's .config file

### ISSUE THREAD

**Issue by timsar2** [adamosoftware/Ginseng8#44]
in build process when it was try to copy the application's .config file
i got this error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	**MSB3030	Could not copy the file** "F:\projects\cSharp\Ginseng8\Ginseng8.Mvc\config.json" **because it was not found**.	Testing	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4582

**Comment by adamosoftware** [comment]
hi there, I should've said something about this in the readme, but the config info is a secret I'm not keeping in source control. I'm running this internally with my team at work. The code is not secret, but the config has a real database connection and other stuff I need to keep out of source control. Let me give some thought as to how I can support your case, though.

**Comment by timsar2** [comment]
So how to create config file?

**Comment by adamosoftware** [comment]
A blank config file wouldn't help you without a blank database. I don't use Entity Framework, so it's a bit of work to create the database (requiring SQL Server background). I would really need to develop a whole "getting starting" guide to help contributors on-board, and unfortunately I just don't have time for that right now. I appreciate your interest in this however. It's clear I need a better guide for people in your situation
